server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
<<<<<<< HEAD
    url: jdbc:postgresql://127.0.0.1:5432/mydb
    #url: jdbc:postgresql://192.168.152.43:5432/mydb
=======
    #url: jdbc:postgresql://127.0.0.1:5432/mydb
    url: jdbc:postgresql://192.168.160.18:5432/mydb
>>>>>>> 717562009e30acc6194396aeab3b9901d5c1bbf3
    username: postgres
    password: postgres
    # druid 链接池配置
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      async-init: true

mybatis-plus:
  mapper-locations: mapper/*.xml
  # 配置实体类包地址
  type-aliases-package: com.example.rbacdemo.model
  # 驼峰转下划线
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 主键策略
      id-type: auto
#      # 表名前缀
#      table-prefix: t
#      # 表名是否使用下划线间隔，默认：是
#      table-underline: true
#  # 添加mybatis配置文件路径
#  config-location: mybatis-config.xml